/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthSuccessRouteImport } from './routes/auth-success'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedSlugRouteImport } from './routes/shared.$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth-success',
  path: '/auth-success',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedSlugRoute = SharedSlugRouteImport.update({
  id: '/shared/$slug',
  path: '/shared/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-success': typeof AuthSuccessRoute
  '/login': typeof LoginRoute
  '/shared/$slug': typeof SharedSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-success': typeof AuthSuccessRoute
  '/login': typeof LoginRoute
  '/shared/$slug': typeof SharedSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-success': typeof AuthSuccessRoute
  '/login': typeof LoginRoute
  '/shared/$slug': typeof SharedSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth-success' | '/login' | '/shared/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth-success' | '/login' | '/shared/$slug'
  id: '__root__' | '/' | '/auth-success' | '/login' | '/shared/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  LoginRoute: typeof LoginRoute
  SharedSlugRoute: typeof SharedSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-success': {
      id: '/auth-success'
      path: '/auth-success'
      fullPath: '/auth-success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$slug': {
      id: '/shared/$slug'
      path: '/shared/$slug'
      fullPath: '/shared/$slug'
      preLoaderRoute: typeof SharedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  LoginRoute: LoginRoute,
  SharedSlugRoute: SharedSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
